### ISSUE TITLE
offer-hook default value not accurate

### ISSUE THREAD

**Issue by Anarkoic** [dexie-space/splash#20]
--offer-hook <OFFER_HOOK>
          HTTP endpoint where incoming offers are posted to, sends JSON body {"offer":"offer1..."} (defaults to STDOUT)

doesn't appear to default to STDOUT
and using STDOUT value gives error:

Error posting to offer hook: builder error: relative URL without a base

**Comment by denisu** [comment]
I think this is a misunderstanding. The app always defaults to STDOUT (it has nothing to do with the `--offer-hook`, which only accepts a HTTP endpoint).

I will remove it from the explanation.

**Comment by denisu** [comment]
fixed in https://github.com/dexie-space/splash/commit/7fac669fdefe59ccb663d50ed935410db7784d82
